name: deploy-client

on:
  push:
    branches:
      - main
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && docker build -t fahimjason/client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      - run: docker push fahimjason/client
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save e-ticketing
      - run: kubectl rollout restart deployment client-depl
