name: deploy-expiration

on:
  push:
    branches:
      - main
    paths:
      - "expiration/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t fahimjason/expiration .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      - run: docker push fahimjason/expiration
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save e-ticketing
      - run: kubectl rollout restart deployment expiration-depl
